# Generated by Django 2.1.dev20180124004857 on 2018-02-02 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='event held time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='last updated time')),
            ],
        ),
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestNumberIsVisible', models.BooleanField()),
                ('guestListIsVisible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MultiChoicesResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('last_updated_time', models.DateTimeField(verbose_name='last updated time')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('S', 'Single select'), ('M', 'Multiple select'), ('T', 'Text')], max_length=1)),
                ('isEditable', models.BooleanField(default=True)),
                ('isOptional', models.BooleanField(default=False)),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='last updated time')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Event')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='time registered')),
                ('identity', models.CharField(choices=[('0', 'Owner'), ('1', 'Vendor'), ('2', 'Guest')], max_length=1, null=True)),
                ('register_state', models.CharField(choices=[('0', 'Pending'), ('1', 'Passed'), ('2', 'Declined and unread'), ('3', 'Declined and read')], max_length=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Event')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.People')),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('last_updated_time', models.DateTimeField(verbose_name='last updated time')),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'T'}, on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question')),
                ('register_event', models.ForeignKey(limit_choices_to={'identity': '2'}, on_delete=django.db.models.deletion.CASCADE, to='RSVP.RegisterEvent')),
            ],
        ),
        migrations.AddField(
            model_name='questionaccess',
            name='registerEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.RegisterEvent'),
        ),
        migrations.AddField(
            model_name='multichoicesresponse',
            name='question',
            field=models.ForeignKey(limit_choices_to={'question_type': 'S'}, on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question'),
        ),
        migrations.AddField(
            model_name='multichoicesresponse',
            name='register_event',
            field=models.ForeignKey(limit_choices_to={'identity': '2'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='RSVP.RegisterEvent'),
        ),
        migrations.AddField(
            model_name='eventaccess',
            name='registerEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.RegisterEvent'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RSVP.People'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(limit_choices_to={'question_type': 'S'}, on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='textresponse',
            unique_together={('question', 'register_event')},
        ),
        migrations.AlterUniqueTogether(
            name='registerevent',
            unique_together={('event', 'people')},
        ),
        migrations.AlterUniqueTogether(
            name='multichoicesresponse',
            unique_together={('question', 'register_event')},
        ),
    ]
