# Generated by Django 2.1.dev20180124004857 on 2018-02-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AlterField(
            model_name='registerevent',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time registered'),
        ),
    ]
