# Generated by Django 2.1.dev20180124004857 on 2018-02-01 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0002_auto_20180201_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event held time'),
        ),
    ]
