# Generated by Django 2.1.dev20180124004857 on 2018-02-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0003_event_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='hello',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
