# Generated by Django 2.1.dev20180124004857 on 2018-02-01 03:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0004_auto_20180201_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hello',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=10),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
