# Generated by Django 2.1.dev20180124004857 on 2018-02-08 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0004_auto_20180207_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoicesresponse',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Choice'),
        ),
    ]
