# Generated by Django 2.1.dev20180124004857 on 2018-02-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0005_auto_20180208_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
