# Generated by Django 2.1.dev20180124004857 on 2018-02-01 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0005_auto_20180201_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
