# Generated by Django 2.1.dev20180124004857 on 2018-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0006_question_isvisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='plus_one_permissible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multichoicesresponse',
            name='is_plus_one',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textresponse',
            name='is_plus_one',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
