# Generated by Django 2.1.dev20180124004857 on 2018-02-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0007_auto_20180209_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multichoicesresponse',
            unique_together={('question', 'register_event', 'is_plus_one')},
        ),
        migrations.AlterUniqueTogether(
            name='textresponse',
            unique_together={('question', 'register_event', 'is_plus_one')},
        ),
    ]
