# Generated by Django 2.1.dev20180124004857 on 2018-02-01 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0007_auto_20180201_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoicesResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30)),
                ('last_updated_time', models.DateTimeField(verbose_name='last updated time')),
            ],
        ),
        migrations.CreateModel(
            name='TextResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=500)),
                ('last_updated_time', models.DateTimeField(verbose_name='last updated time')),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
        migrations.AddField(
            model_name='textresponse',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.People'),
        ),
        migrations.AddField(
            model_name='textresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question'),
        ),
        migrations.AddField(
            model_name='multichoicesresponse',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.People'),
        ),
        migrations.AddField(
            model_name='multichoicesresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RSVP.Question'),
        ),
    ]
