# Generated by Django 2.1.dev20180124004857 on 2018-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0008_auto_20180209_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('S', 'Single select'), ('T', 'Text')], max_length=1),
        ),
    ]
