# Generated by Django 2.1.dev20180124004857 on 2018-02-11 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0009_auto_20180209_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventaccess',
            name='registerEvent',
        ),
        migrations.RemoveField(
            model_name='questionaccess',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionaccess',
            name='registerEvent',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='plus_one_permissible',
            field=models.BooleanField(verbose_name='Is guest allowed to bring a plus one?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isOptional',
            field=models.BooleanField(default=False, verbose_name='Is this a required question?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='Are vendors allowed to view this question?'),
        ),
        migrations.DeleteModel(
            name='EventAccess',
        ),
        migrations.DeleteModel(
            name='QuestionAccess',
        ),
    ]
