# Generated by Django 2.1.dev20180124004857 on 2018-02-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RSVP', '0010_auto_20180211_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='isOptional',
        ),
    ]
